"use client";
import {useState} from "react";
import {TaskForm} from "../../task-form";
import {useWorkspace,WorkspaceState,type Task} from "../../workspace-store";

export default function SprintBacklogPage(){
 const {tasks,sprints,save}=useWorkspace();
 const openSprints=sprints.filter(s=>s.status!=="closed");
 const [sprintId,setSprintId]=useState("");
 const active=openSprints.find(s=>s.id===sprintId)||openSprints.find(s=>s.status==="active")||openSprints[0];
 const [selected,setSelected]=useState<Task|undefined>();const [query,setQuery]=useState("");
 const sprintTasks=tasks.filter(t=>t.sprint_id===active?.id&&(t.title+t.code).toLowerCase().includes(query.toLowerCase()));
 const candidates=tasks.filter(t=>!t.sprint_id&&t.status!=="Completado");const points=sprintTasks.reduce((sum,t)=>sum+t.story_points,0);const completed=sprintTasks.filter(t=>t.status==="Completado").length;
 const updateSprint=async(task:Task,include:boolean)=>save("task",{...task,sprint_id:include?active?.id:null,status:include&&["Ideas","Backlog"].includes(task.status)?"Sprint actual":task.status});
 return <WorkspaceState><div className="workspace-heading"><div><span className="admin-eyebrow">Planificación</span><h1>Sprint Backlog</h1><p>Selecciona un Sprint abierto y administra su compromiso.</p></div>{active&&<a className="secondary-button sprint-link" href="/admin/sprint">Ver historial →</a>}</div>{!active?<div className="workspace-state">No hay Sprints abiertos. Crea o reabre uno para planificar.</div>:<><div className="sprint-selector"><label>Sprint seleccionado<select value={active.id} onChange={e=>setSprintId(e.target.value)}>{openSprints.map(s=><option value={s.id} key={s.id}>{s.name} · {s.status==="active"?"Abierto":"Planificado"}</option>)}</select></label><span>{active.goal}</span></div><section className="stat-grid four sprint-backlog-stats">{[[sprintTasks.length,"Historias","comprometidas"],[points,"Puntos","capacidad total"],[completed,"Completadas",`de ${sprintTasks.length}`],[sprintTasks.length?Math.round(sprintTasks.reduce((sum,t)=>sum+t.progress,0)/sprintTasks.length):0,"Progreso","promedio"]].map(([value,label,detail])=><article className="stat-card" key={label}><small>{label}</small><strong>{value}{label==="Progreso"?"%":""}</strong><span>{detail}</span></article>)}</section><div className="sprint-backlog-layout"><section><div className="backlog-section-head"><div><h2>{active.name}</h2><p>Trabajo comprometido en este Sprint.</p></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar…" aria-label="Buscar en Sprint Backlog"/></div><div className="sprint-task-list">{sprintTasks.map(task=><article key={task.id}><button className="sprint-task-main" onClick={()=>setSelected(task)}><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span><span><b>{task.code} · {task.title}</b><small>{task.status} · {task.assignee_name||"Sin asignar"}</small></span></button><span>{task.story_points} pts</span><div className="progress"><i style={{width:`${task.progress}%`}}/></div><button className="remove-sprint" onClick={()=>void updateSprint(task,false)}>Sacar</button></article>)}</div></section><aside className="workspace-panel sprint-candidates"><header><h2>Disponibles para añadir</h2><span>{candidates.length}</span></header><p>Historias que todavía no pertenecen a otro Sprint.</p>{candidates.map(task=><article key={task.id}><span><b>{task.title}</b><small>{task.code} · {task.story_points} pts</small></span><button className="admin-primary compact" onClick={()=>void updateSprint(task,true)}>+ Añadir</button></article>)}</aside></div></>}{selected&&<TaskForm task={selected} onClose={()=>setSelected(undefined)}/>}</WorkspaceState>
}
