"use client";
import { useState,type FormEvent } from "react";
import { Modal,useWorkspace,type Task } from "./workspace-store";
export const taskStatuses=["Ideas","Backlog","Sprint actual","En desarrollo","Code Review","Testing","Completado"];

export function TaskForm({task,onClose}:{task?:Task;onClose:()=>void}){
 const {members,sprints,save,remove}=useWorkspace();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [assignees,setAssignees]=useState<string[]>(task?.assignee_ids?.length?task.assignee_ids:task?.assignee_id?[task.assignee_id]:[]);
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");const f=new FormData(event.currentTarget);try{await save("task",{id:task?.id,title:f.get("title"),description:f.get("description"),status:f.get("status"),priority:f.get("priority"),tag:f.get("tag"),story_points:Number(f.get("story_points")),progress:Number(f.get("progress")),due_on:f.get("due_on"),assignee_ids:assignees,sprint_id:f.get("sprint_id")});onClose()}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar.")}finally{setBusy(false)}};
 const destroy=async()=>{if(!task||!confirm("¿Eliminar esta tarea permanentemente?"))return;setBusy(true);try{await remove("task",task.id);onClose()}catch(e){setError(e instanceof Error?e.message:"No se pudo eliminar.")}finally{setBusy(false)}};
 return <Modal title={task?`Editar ${task.code}`:"Nueva tarea"} onClose={onClose}><form className="workspace-form" onSubmit={submit}><label>Título<input name="title" defaultValue={task?.title} required maxLength={220}/></label><label className="full">Descripción<textarea name="description" defaultValue={task?.description} rows={4}/></label><label>Estado<select name="status" defaultValue={task?.status||"Ideas"}>{taskStatuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Prioridad<select name="priority" defaultValue={task?.priority||"Media"}>{["Baja","Media","Alta","Crítica"].map(x=><option key={x}>{x}</option>)}</select></label><label>Etiqueta<input name="tag" defaultValue={task?.tag||"Producto"}/></label><fieldset className="assignee-picker"><legend>Responsables</legend><div>{members.map(member=><label key={member.id}><input type="checkbox" checked={assignees.includes(member.id)} onChange={()=>setAssignees(current=>current.includes(member.id)?current.filter(id=>id!==member.id):[...current,member.id])}/><span>{member.name}<small>{member.role}</small></span></label>)}</div><small>{assignees.length?`${assignees.length} persona${assignees.length===1?"":"s"} asignada${assignees.length===1?"":"s"}`:"Sin responsables"}</small></fieldset><label>Sprint<select name="sprint_id" defaultValue={task?.sprint_id||""}><option value="">Sin sprint</option>{sprints.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Fecha límite<input name="due_on" type="date" defaultValue={task?.due_on?.slice(0,10)||""}/></label><label>Puntos<input name="story_points" type="number" min="0" max="100" defaultValue={task?.story_points||1}/></label><label>Progreso (%)<input name="progress" type="number" min="0" max="100" defaultValue={task?.progress||0}/></label>{error&&<p className="admin-error full" role="alert">{error}</p>}<footer className="form-actions full">{task&&<button className="danger-button" type="button" onClick={destroy}>Eliminar</button>}<button className="secondary-button" type="button" onClick={onClose}>Cancelar</button><button className="admin-primary" disabled={busy}>{busy?"Guardando…":"Guardar tarea"}</button></footer></form></Modal>
}
