"use client";
import {useState,type FormEvent} from "react";
import {Modal,useWorkspace,WorkspaceState,type Sprint} from "../../workspace-store";

const statusLabel:Record<string,string>={active:"Abierto",planned:"Planificado",closed:"Cerrado"};

export default function SprintPage(){
 const {sprints,tasks,save}=useWorkspace();const [selectedId,setSelectedId]=useState("");const [editing,setEditing]=useState<Sprint|null|undefined>();
 const selected=sprints.find(s=>s.id===selectedId)||sprints.find(s=>s.status==="active")||sprints[0];
 const sprintTasks=selected?tasks.filter(t=>t.sprint_id===selected.id):[];const done=sprintTasks.filter(t=>t.status==="Completado").length;const blocked=sprintTasks.filter(t=>t.priority==="Crítica"&&t.progress<100).length;const progress=sprintTasks.length?Math.round(sprintTasks.reduce((a,t)=>a+t.progress,0)/sprintTasks.length):0;
 return <WorkspaceState><div className="workspace-heading"><div><span className="admin-eyebrow">Historial de trabajo</span><h1>Sprints</h1><p>Mantén varios Sprints abiertos y conserva los cerrados como documentación.</p></div><button className="admin-primary" onClick={()=>setEditing(null)}>+ Nuevo Sprint</button></div>
  {sprints.length>0&&<div className="sprint-tabs" role="tablist" aria-label="Seleccionar Sprint">{sprints.map(s=><button role="tab" aria-selected={selected?.id===s.id} className={selected?.id===s.id?"is-selected":""} onClick={()=>setSelectedId(s.id)} key={s.id}><span><b>{s.name}</b><small>{new Date(s.starts_on).toLocaleDateString("es")} — {new Date(s.ends_on).toLocaleDateString("es")}</small></span><i className={`sprint-status ${s.status}`}>{statusLabel[s.status]||s.status}</i></button>)}</div>}
  {!selected?<div className="workspace-state">Todavía no hay Sprints. Crea el primero para comenzar.</div>:<><div className="workspace-heading sprint-detail-heading"><div><span className={`sprint-status ${selected.status}`}>{statusLabel[selected.status]}</span><h2>{selected.name}</h2><p>{selected.goal}</p></div><div className="heading-actions"><button className="secondary-button" onClick={()=>setEditing(selected)}>Editar</button>{selected.status==="closed"?<button className="admin-primary" onClick={()=>void save("sprint",{...selected,status:"active"})}>Reabrir Sprint</button>:<button className="admin-primary" onClick={()=>void save("sprint",{...selected,status:"closed"})}>Cerrar Sprint</button>}</div></div><section className="workspace-panel sprint-hero"><div><small>Objetivo documentado</small><h2>{selected.goal||"Sin objetivo definido"}</h2></div><strong>{progress}%</strong><div className="progress"><i style={{width:`${progress}%`}}/></div></section><section className="stat-grid four"><article className="stat-card"><small>Velocidad</small><strong>{selected.points}</strong><span>puntos</span></article><article className="stat-card"><small>Completadas</small><strong>{done}</strong><span>historias</span></article><article className="stat-card"><small>Pendientes</small><strong>{sprintTasks.length-done}</strong><span>historias</span></article><article className="stat-card"><small>Críticas activas</small><strong>{blocked}</strong><span>requieren atención</span></article></section><section className="workspace-panel sprint-documentation"><header><h2>Historias del Sprint</h2><a href="/admin/sprint-backlog">Gestionar backlog</a></header>{sprintTasks.length?sprintTasks.map(task=><p key={task.id}><span><b>{task.code} · {task.title}</b><small>{task.assignee_name||"Sin asignar"} · {task.status}</small></span><strong>{task.progress}%</strong></p>):<div className="empty-inline">Este Sprint no tiene historias asignadas.</div>}</section></>}
  {editing!==undefined&&<SprintModal sprint={editing||undefined} close={()=>setEditing(undefined)}/>}</WorkspaceState>
}

function SprintModal({sprint,close}:{sprint?:Sprint;close:()=>void}){const {save,remove}=useWorkspace();const [error,setError]=useState("");const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await save("sprint",{id:sprint?.id,name:f.get("name"),goal:f.get("goal"),starts_on:f.get("starts_on"),ends_on:f.get("ends_on"),status:f.get("status")});close()}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo guardar el Sprint.")}};const destroy=async()=>{if(!sprint||!confirm(`¿Eliminar “${sprint.name}”? Sus historias no se borrarán; volverán al Product Backlog.`))return;try{await remove("sprint",sprint.id);close()}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo eliminar el Sprint.")}};return <Modal title={sprint?"Editar Sprint":"Nuevo Sprint"} onClose={close}><form className="workspace-form" onSubmit={submit}><label>Nombre<input name="name" defaultValue={sprint?.name} placeholder="Sprint 05" required autoFocus/></label><label>Estado<select name="status" defaultValue={sprint?.status||"active"}><option value="active">Abierto</option><option value="planned">Planificado</option><option value="closed">Cerrado</option></select></label><label>Inicio<input type="date" name="starts_on" defaultValue={sprint?.starts_on?.slice(0,10)} required/></label><label>Cierre<input type="date" name="ends_on" defaultValue={sprint?.ends_on?.slice(0,10)} required/></label><label className="full">Objetivo<textarea name="goal" rows={5} defaultValue={sprint?.goal} placeholder="¿Qué resultado debe entregar este Sprint?"/></label>{error&&<p className="admin-error full">{error}</p>}<footer className="form-actions full">{sprint&&<button type="button" className="danger-button" onClick={()=>void destroy()}>Eliminar Sprint</button>}<button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="admin-primary">Guardar Sprint</button></footer></form></Modal>}
