"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {CalendarPlus,Download,Upload} from "lucide-react";
import {Modal,useWorkspace,WorkspaceState,type WorkspaceEvent} from "../../workspace-store";

const monthLabel=(date:Date)=>date.toLocaleDateString("es-DO",{month:"long",year:"numeric"});
const isoDate=(year:number,month:number,day:number)=>`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`;

export default function CalendarPage(){
 const {events,save,remove}=useWorkspace();
 const today=new Date();
 const [viewDate,setViewDate]=useState(()=>new Date(today.getFullYear(),today.getMonth(),1));
 const [current,setCurrent]=useState<WorkspaceEvent|null|undefined>();
 const [calendarError,setCalendarError]=useState("");
 const [google,setGoogle]=useState<{configured:boolean;connected:boolean;email?:string;lastSync?:string}|null>(null),[syncing,setSyncing]=useState(false),[syncMessage,setSyncMessage]=useState("");
 const importInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{void fetch("/api/admin/calendar/google",{cache:"no-store"}).then(response=>response.json()).then(result=>{if(result.ok)setGoogle(result)}).catch(()=>undefined)},[]);
 const year=viewDate.getFullYear(),month=viewDate.getMonth();
 const days=new Date(year,month+1,0).getDate();
 const offset=(new Date(year,month,1).getDay()+6)%7;
 const isCurrentMonth=year===today.getFullYear()&&month===today.getMonth();
 const suggestedDate=isoDate(year,month,isCurrentMonth?today.getDate():1);
 const move=(amount:number)=>setViewDate(date=>new Date(date.getFullYear(),date.getMonth()+amount,1));
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await save("event",{id:current?.id,title:f.get("title"),event_date:f.get("event_date"),event_time:f.get("event_time"),kind:f.get("kind")});setCurrent(undefined)};
 const exportCalendar=()=>{const rows=events.map(event=>{const date=event.event_date.slice(0,10).replaceAll("-","");const time=event.event_time?event.event_time.slice(0,5).replace(":","")+"00":"";return [`BEGIN:VEVENT`,`UID:${event.id}@meridian-ai-rd`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"")}`,time?`DTSTART:${date}T${time}`:`DTSTART;VALUE=DATE:${date}`,`SUMMARY:${event.title.replaceAll("\n"," ")}`,`CATEGORIES:${event.kind}`,`END:VEVENT`].join("\r\n")}).join("\r\n");const blob=new Blob([`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Meridian//Workspace//ES\r\n${rows}\r\nEND:VCALENDAR`],{type:"text/calendar"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="meridian-workspace.ics";anchor.click();URL.revokeObjectURL(url)};
 const importCalendar=async(file?:File)=>{if(!file)return;setCalendarError("");try{const text=await file.text(),blocks=text.match(/BEGIN:VEVENT[\s\S]*?END:VEVENT/g)||[];if(!blocks.length)throw new Error("El archivo no contiene eventos compatibles.");for(const block of blocks){const title=block.match(/^SUMMARY:(.+)$/m)?.[1]?.trim(),raw=block.match(/^DTSTART(?:;VALUE=DATE)?:(\d{8})(?:T(\d{4}))?/m);if(!title||!raw)continue;await save("event",{title,event_date:`${raw[1].slice(0,4)}-${raw[1].slice(4,6)}-${raw[1].slice(6,8)}`,event_time:raw[2]?`${raw[2].slice(0,2)}:${raw[2].slice(2,4)}`:"",kind:block.match(/^CATEGORIES:(.+)$/m)?.[1]?.trim()||"Evento importado"})}}catch(reason){setCalendarError(reason instanceof Error?reason.message:"No se pudo importar el calendario.")}finally{if(importInput.current)importInput.current.value=""}};
 const googleUrl=(event:WorkspaceEvent)=>{const date=event.event_date.slice(0,10).replaceAll("-","");const time=event.event_time?.slice(0,5).replace(":","");const dates=time?`${date}T${time}00/${date}T${time}00`:`${date}/${date}`;return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(event.title)}&dates=${dates}&details=${encodeURIComponent(`Evento de Meridian Workspace · ${event.kind}`)}`};
 const syncGoogle=async()=>{setSyncing(true);setCalendarError("");setSyncMessage("");try{const response=await fetch("/api/admin/calendar/google",{method:"POST"}),result=await response.json();if(!response.ok)throw new Error(result.error);setSyncMessage(`${result.synced} eventos sincronizados con Google Calendar.`);setGoogle(value=>value?{...value,lastSync:new Date().toISOString()}:value)}catch(reason){setCalendarError(reason instanceof Error?reason.message:"No se pudo sincronizar Google Calendar.")}finally{setSyncing(false)}};
 return <WorkspaceState>
  <div className="workspace-heading calendar-heading"><div><span className="admin-eyebrow">Planificación del equipo</span><h1>Calendario Scrum</h1><p>Ceremonias, entregas y fechas importantes de cualquier mes.</p>{google?.connected&&<small className="google-connection">Google conectado: {google.email}</small>}</div><div className="heading-actions calendar-actions"><input ref={importInput} hidden type="file" accept=".ics,text/calendar" onChange={event=>void importCalendar(event.target.files?.[0])}/>{google?.connected?<button className="google-sync-button" disabled={syncing} onClick={()=>void syncGoogle()}><CalendarPlus size={16}/>{syncing?"Sincronizando…":"Sincronizar Google"}</button>:<button className="google-sync-button" disabled={google?.configured===false} onClick={()=>{window.location.href="/api/admin/calendar/google/start"}}><CalendarPlus size={16}/>{google?.configured===false?"Google sin configurar":"Conectar Google"}</button>}<button className="secondary-button" onClick={()=>importInput.current?.click()}><Upload size={16}/> Importar .ics</button><button className="secondary-button" onClick={exportCalendar}><Download size={16}/> Exportar</button><button className="admin-primary" onClick={()=>setCurrent(null)}>+ Nuevo evento</button></div></div>
  {calendarError&&<p className="admin-error docs-alert">{calendarError}</p>}
  {syncMessage&&<p className="calendar-success">{syncMessage}</p>}
  <div className="calendar-toolbar"><div><button onClick={()=>move(-1)} aria-label="Mes anterior">←</button><button className="today-button" onClick={()=>setViewDate(new Date(today.getFullYear(),today.getMonth(),1))}>Hoy</button><button onClick={()=>move(1)} aria-label="Mes siguiente">→</button></div><h2>{monthLabel(viewDate)}</h2><span>{events.filter(event=>{const date=new Date(`${event.event_date.slice(0,10)}T12:00:00`);return date.getFullYear()===year&&date.getMonth()===month}).length} eventos</span></div>
  <div className="calendar"><header>{["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map(x=><b key={x}>{x}</b>)}</header><div className="calendar-grid">{Array.from({length:Math.ceil((offset+days)/7)*7},(_,i)=>{const day=i-offset+1;const date=isoDate(year,month,day);const valid=day>0&&day<=days;const dayEvents=valid?events.filter(x=>x.event_date.slice(0,10)===date):[];const isToday=valid&&date===isoDate(today.getFullYear(),today.getMonth(),today.getDate());return <article className={!valid?"outside":isToday?"is-today":""} key={i}><span>{valid?day:""}</span>{dayEvents.map(x=><button className="calendar-event" key={x.id} onClick={()=>setCurrent(x)} title={`${x.kind}${x.event_time?` · ${x.event_time.slice(0,5)}`:""}`}>{x.title}</button>)}</article>})}</div></div>
  {current!==undefined&&<Modal title={current?"Editar evento":"Nuevo evento"} onClose={()=>setCurrent(undefined)}><form className="workspace-form" onSubmit={submit}><label className="full">Título<input name="title" defaultValue={current?.title} required autoFocus/></label><label>Fecha<input name="event_date" type="date" defaultValue={current?.event_date?.slice(0,10)||suggestedDate} required/></label><label>Hora<input name="event_time" type="time" defaultValue={current?.event_time?.slice(0,5)||""}/></label><label>Tipo<select name="kind" defaultValue={current?.kind||"Evento"}>{["Evento","Daily Scrum","Sprint Planning","Sprint Review","Retrospectiva","Entrega","Fecha límite"].map(type=><option key={type}>{type}</option>)}</select></label>{current&&<a className="google-calendar-link full" href={googleUrl(current)} target="_blank" rel="noreferrer"><CalendarPlus size={17}/> Añadir este evento a Google Calendar</a>}<footer className="form-actions full">{current&&<button type="button" className="danger-button" onClick={async()=>{if(confirm("¿Eliminar evento?")){await remove("event",current.id);setCurrent(undefined)}}}>Eliminar</button>}<button type="button" className="secondary-button" onClick={()=>setCurrent(undefined)}>Cancelar</button><button className="admin-primary">Guardar evento</button></footer></form></Modal>}
 </WorkspaceState>
}
