import {createCipheriv,createDecipheriv,createHash,randomBytes} from "node:crypto";
import {adminDb} from "@/lib/admin-db";

const key=()=>{const value=process.env.GOOGLE_CALENDAR_TOKEN_KEY;if(!value)throw new Error("GOOGLE_CALENDAR_TOKEN_KEY no está configurada");return createHash("sha256").update(value).digest()};
export const googleConfigured=()=>Boolean(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET&&process.env.GOOGLE_CALENDAR_TOKEN_KEY);
export const googleRedirectUri=()=>process.env.GOOGLE_REDIRECT_URI||"https://meridian-ai-rd.vercel.app/api/admin/calendar/google/callback";
export async function ensureGoogleCalendarSchema(){const sql=adminDb();await sql`create table if not exists workspace_google_calendar_connections(user_id uuid primary key references admin_users(id) on delete cascade,google_email text,access_token text not null,refresh_token text not null,expires_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now())`;await sql`create table if not exists workspace_google_event_links(user_id uuid not null references admin_users(id) on delete cascade,workspace_event_id uuid not null references workspace_events(id) on delete cascade,google_event_id text not null,updated_at timestamptz not null default now(),primary key(user_id,workspace_event_id))`}
export function encryptToken(value:string){const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key(),iv),encrypted=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]),tag=cipher.getAuthTag();return Buffer.concat([iv,tag,encrypted]).toString("base64url")}
export function decryptToken(value:string){const data=Buffer.from(value,"base64url"),iv=data.subarray(0,12),tag=data.subarray(12,28),encrypted=data.subarray(28),decipher=createDecipheriv("aes-256-gcm",key(),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(encrypted),decipher.final()]).toString("utf8")}
export async function accessTokenFor(userId:string){await ensureGoogleCalendarSchema();const sql=adminDb(),rows=await sql`select access_token,refresh_token,expires_at from workspace_google_calendar_connections where user_id=${userId} limit 1`;if(!rows.length)throw new Error("Google Calendar no está conectado");const row=rows[0];if(new Date(row.expires_at).getTime()>Date.now()+60000)return decryptToken(row.access_token);const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID!,client_secret:process.env.GOOGLE_CLIENT_SECRET!,refresh_token:decryptToken(row.refresh_token),grant_type:"refresh_token"})}),tokens=await response.json();if(!response.ok)throw new Error(tokens.error_description||"No se pudo renovar la conexión con Google");await sql`update workspace_google_calendar_connections set access_token=${encryptToken(tokens.access_token)},expires_at=${new Date(Date.now()+Number(tokens.expires_in||3600)*1000).toISOString()},updated_at=now() where user_id=${userId}`;return tokens.access_token as string}
