"use client";
import Link from "next/link";
import {Bell,CalendarDays,Code2,Contrast,ExternalLink,UsersRound} from "lucide-react";
import {useEffect,useState} from "react";

type Preferences={monochrome:boolean;sounds:boolean;reducedMotion:boolean;compact:boolean};
const defaults:Preferences={monochrome:false,sounds:true,reducedMotion:false,compact:false};
const read=():Preferences=>{try{return {...defaults,...JSON.parse(localStorage.getItem("meridian-preferences")||"{}")}}catch{return defaults}};

export default function SettingsPage(){
 const [preferences,setPreferences]=useState(defaults),[notice,setNotice]=useState("");
 useEffect(()=>{const timer=window.setTimeout(()=>setPreferences(read()),0);return()=>window.clearTimeout(timer)},[]);
 const update=(key:keyof Preferences,value:boolean)=>{const next={...preferences,[key]:value};setPreferences(next);localStorage.setItem("meridian-preferences",JSON.stringify(next));window.dispatchEvent(new CustomEvent("meridian-preferences",{detail:next}));setNotice("Preferencia guardada")};
 const notifications=async()=>{if(!("Notification" in window)){setNotice("Este navegador no admite notificaciones.");return}const permission=await Notification.requestPermission();setNotice(permission==="granted"?"Notificaciones activadas":"No se concedió permiso para notificaciones")};
 return <><div className="workspace-heading"><div><span className="admin-eyebrow">Administración</span><h1>Configuración</h1><p>Preferencias reales del Workspace e integraciones del equipo.</p></div>{notice&&<span className="settings-saved">{notice}</span>}</div>
 <div className="settings-sections">
  <section className="workspace-panel"><header><span><Contrast size={20}/><b>Apariencia</b></span></header><div className="settings-controls"><Toggle label="Modo oscuro obsidiana" text="Usa una interfaz negra de alto contraste en todo el Workspace." checked={preferences.monochrome} onChange={value=>update("monochrome",value)}/><Toggle label="Vista compacta" text="Reduce espacios para mostrar más información." checked={preferences.compact} onChange={value=>update("compact",value)}/><Toggle label="Reducir movimiento" text="Desactiva animaciones y transiciones." checked={preferences.reducedMotion} onChange={value=>update("reducedMotion",value)}/></div></section>
  <section className="workspace-panel"><header><span><Bell size={20}/><b>Notificaciones</b></span></header><div className="settings-controls"><Toggle label="Sonidos del chat" text="Reproduce una alerta al recibir mensajes." checked={preferences.sounds} onChange={value=>update("sounds",value)}/><article><span><b>Notificaciones del navegador</b><small>Recibe mensajes aunque tengas otra pestaña abierta.</small></span><button className="secondary-button" onClick={notifications}>Activar</button></article></div></section>
  <section className="workspace-panel"><header><span><UsersRound size={20}/><b>Equipo y permisos</b></span></header><div className="settings-controls"><article><span><b>Usuarios del Workspace</b><small>Gestiona miembros, roles, disponibilidad y carga.</small></span><Link className="secondary-button" href="/admin/equipo">Administrar</Link></article><article><span><b>Perfil y seguridad</b><small>Consulta el rol y la sesión de tu cuenta.</small></span><Link className="secondary-button" href="/admin/perfil">Abrir perfil</Link></article></div></section>
  <section className="workspace-panel"><header><span><CalendarDays size={20}/><b>Integraciones</b></span></header><div className="settings-controls"><article><span><b>Google Calendar</b><small>Importa/exporta calendarios y añade eventos a Google.</small></span><Link className="secondary-button" href="/admin/calendario">Configurar</Link></article><article><span><b>GitHub</b><small>Repositorio público de Meridian.</small></span><a className="secondary-button" href="https://github.com/DaniDRK20/meridian-landing-page" target="_blank" rel="noreferrer"><Code2 size={16}/> Abrir</a></article><article><span><b>Figma</b><small>Abre el espacio de diseño para conectar un archivo.</small></span><a className="secondary-button" href="https://www.figma.com/files" target="_blank" rel="noreferrer"><ExternalLink size={15}/> Abrir</a></article><article><span><b>Slack y Discord</b><small>Las alertas externas requieren un webhook del equipo.</small></span><a className="secondary-button" href="https://api.slack.com/apps" target="_blank" rel="noreferrer"><ExternalLink size={15}/> Configurar</a></article></div></section>
 </div></>;
}

function Toggle({label,text,checked,onChange}:{label:string;text:string;checked:boolean;onChange:(value:boolean)=>void}){return <article><span><b>{label}</b><small>{text}</small></span><label className="settings-toggle"><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><i/><span>{checked?"Sí":"No"}</span></label></article>}
