"use client";
import {useState,type FormEvent} from "react";
import {Modal,useWorkspace,WorkspaceState,type Member} from "../../workspace-store";
import {useWorkspacePresence} from "../../realtime-provider";

export default function TeamPage(){
 const {members,save,remove}=useWorkspace(),presence=useWorkspacePresence();const [current,setCurrent]=useState<Member|null|undefined>();
 const statusFor=(member:Member)=>presence.find(item=>(member.email&&item.email.toLowerCase()===member.email.toLowerCase())||item.name.toLowerCase()===member.name.toLowerCase())?.state||"offline";
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await save("member",{id:current?.id,name:f.get("name"),role:f.get("role"),email:f.get("email"),availability:f.get("availability"),workload:Number(f.get("workload"))});setCurrent(undefined)};
 return <WorkspaceState><div className="workspace-heading"><div><span className="admin-eyebrow">Equipo</span><h1>Personas que construyen Meridian</h1><p>Capacidad, trabajo asignado y presencia en tiempo real.</p></div><button className="admin-primary" onClick={()=>setCurrent(null)}>+ Integrante</button></div><div className="team-grid">{members.map(m=>{const status=statusFor(m);return <article className="team-card" key={m.id} onClick={()=>setCurrent(m)}><div className="team-head"><span className={`avatar large presence-${status}`}>{m.name.slice(0,2)}<i/></span><span><h2>{m.name}</h2><p>{m.role}</p><small className={`member-presence ${status}`}><i/>{status==="active"?"Activo ahora":status==="away"?"Ausente":"Desconectado"}</small></span><i className={m.availability==="Disponible"?"available":"focus"}>{m.availability}</i></div><div className="load"><span>Carga de trabajo <b>{m.workload}%</b></span><div className="progress"><i style={{width:`${m.workload}%`}}/></div></div><dl><div><dt>Tareas</dt><dd>{m.task_count}</dd></div><div><dt>Completadas</dt><dd>{m.completed_count}</dd></div><div><dt>Pendientes</dt><dd>{m.task_count-m.completed_count}</dd></div></dl></article>})}</div>{current!==undefined&&<Modal title={current?"Editar integrante":"Nuevo integrante"} onClose={()=>setCurrent(undefined)}><form className="workspace-form" onSubmit={submit}><label>Nombre<input name="name" defaultValue={current?.name} required/></label><label>Rol<input name="role" defaultValue={current?.role} required/></label><label>Correo<input name="email" type="email" defaultValue={current?.email||""}/></label><label>Disponibilidad<select name="availability" defaultValue={current?.availability||"Disponible"}><option>Disponible</option><option>En foco</option><option>No disponible</option></select></label><label>Carga (%)<input name="workload" type="number" min="0" max="100" defaultValue={current?.workload||0}/></label><footer className="form-actions full">{current&&<button type="button" className="danger-button" onClick={async()=>{if(confirm("¿Eliminar integrante?")){await remove("member",current.id);setCurrent(undefined)}}}>Eliminar</button>}<button className="admin-primary">Guardar</button></footer></form></Modal>}</WorkspaceState>
}
