import {NextResponse} from "next/server";
import {adminDb} from "@/lib/admin-db";
import {getAdminSession} from "@/lib/admin-session";
import {accessTokenFor,ensureGoogleCalendarSchema,googleConfigured} from "@/lib/google-calendar";

const validDate=(value:unknown)=>{const match=String(value??"").match(/\d{4}-\d{2}-\d{2}/);if(!match)throw new Error("Un evento tiene una fecha inválida.");return match[0]};
const validTime=(value:unknown)=>{const match=String(value??"").match(/^([01]\d|2[0-3]):([0-5]\d)/);return match?`${match[1]}:${match[2]}`:null};

export async function GET(){const user=await getAdminSession();if(!user)return NextResponse.json({ok:false},{status:401});if(!googleConfigured())return NextResponse.json({ok:true,configured:false,connected:false});await ensureGoogleCalendarSchema();const sql=adminDb(),rows=await sql`select google_email,updated_at from workspace_google_calendar_connections where user_id=${user.id} limit 1`;return NextResponse.json({ok:true,configured:true,connected:Boolean(rows.length),email:rows[0]?.google_email||null,lastSync:rows[0]?.updated_at||null})}
export async function DELETE(){const user=await getAdminSession();if(!user)return NextResponse.json({ok:false},{status:401});await ensureGoogleCalendarSchema();const sql=adminDb();await sql`delete from workspace_google_calendar_connections where user_id=${user.id}`;return NextResponse.json({ok:true})}
export async function POST(){
 const user=await getAdminSession();if(!user)return NextResponse.json({ok:false,error:"No autorizado."},{status:401});if(!googleConfigured())return NextResponse.json({ok:false,error:"Google Calendar no está configurado."},{status:503});
 try{const token=await accessTokenFor(user.id),sql=adminDb(),events=await sql`select * from workspace_events order by event_date,event_time nulls last`,links=await sql`select workspace_event_id,google_event_id from workspace_google_event_links where user_id=${user.id}`,mapped=new Map(links.map(row=>[String(row.workspace_event_id),String(row.google_event_id)]));let synced=0;
 for(const event of events){const date=validDate(event.event_date),time=validTime(event.event_time),start=time?new Date(`${date}T${time}:00-04:00`):null;if(start&&Number.isNaN(start.getTime()))throw new Error(`La hora del evento “${event.title}” no es válida.`);const end=start?new Date(start.getTime()+60*60*1000):null,nextDate=new Date(`${date}T12:00:00Z`);nextDate.setUTCDate(nextDate.getUTCDate()+1);const body={summary:event.title,description:`Meridian Workspace · ${event.kind}`,start:start?{dateTime:start.toISOString(),timeZone:"America/Santo_Domingo"}:{date},end:end?{dateTime:end.toISOString(),timeZone:"America/Santo_Domingo"}:{date:nextDate.toISOString().slice(0,10)},extendedProperties:{private:{meridianWorkspaceId:String(event.id)}}};let googleId=mapped.get(String(event.id)),response=googleId?await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events/${encodeURIComponent(googleId)}`,{method:"PUT",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body)}):null;if(!response||response.status===404){response=await fetch("https://www.googleapis.com/calendar/v3/calendars/primary/events",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body)})}const result=await response.json();if(!response.ok)throw new Error(result.error?.message||"Google rechazó un evento");googleId=result.id;await sql`insert into workspace_google_event_links(user_id,workspace_event_id,google_event_id) values(${user.id},${event.id},${googleId}) on conflict(user_id,workspace_event_id) do update set google_event_id=excluded.google_event_id,updated_at=now()`;synced++}
 await sql`update workspace_google_calendar_connections set updated_at=now() where user_id=${user.id}`;return NextResponse.json({ok:true,synced})}catch(reason){return NextResponse.json({ok:false,error:reason instanceof Error?reason.message:"No se pudo sincronizar."},{status:500})}
}
