"use client";
import {useMemo,useRef,useState,type FormEvent} from "react";
import {Download,FileText,Trash2,Upload} from "lucide-react";
import {Modal,useWorkspace,WorkspaceState,type WorkspaceDocument} from "../../workspace-store";

type Draft={title:string;category:string;content:string};
export default function DocsPage(){
 const {documents,save,remove}=useWorkspace(),fileInput=useRef<HTMLInputElement>(null);
 const [query,setQuery]=useState(""),[current,setCurrent]=useState<WorkspaceDocument|null|undefined>(),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const filtered=useMemo(()=>documents.filter(x=>(x.title+x.category+x.content).toLowerCase().includes(query.toLowerCase())),[documents,query]);
 const close=()=>{setCurrent(undefined);setDraft(null);setError("")};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await save("document",{id:current?.id,title:f.get("title"),category:f.get("category"),content:f.get("content")});close()};
 const importFile=async(file?:File)=>{if(!file)return;setBusy(true);setError("");try{const body=new FormData();body.set("file",file,file.name);const response=await fetch(new URL("/api/admin/documents/import",window.location.origin),{method:"POST",body}),result=await response.json().catch(()=>({error:"El servidor no pudo procesar este archivo."}));if(!response.ok)throw new Error(result.error||"No se pudo importar el archivo.");setDraft({title:result.title,category:result.category,content:result.content});setCurrent(null)}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo importar el archivo.")}finally{setBusy(false);if(fileInput.current)fileInput.current.value=""}};
 return <WorkspaceState>
  <div className="workspace-heading"><div><span className="admin-eyebrow">Centro de conocimiento</span><h1>Documentación</h1><p>Crea, importa y exporta la fuente de verdad del producto.</p></div><div className="heading-actions docs-actions"><input ref={fileInput} type="file" hidden accept=".txt,.md,.markdown,.docx,.pdf" onChange={e=>void importFile(e.target.files?.[0])}/><button className="secondary-button" disabled={busy} onClick={()=>fileInput.current?.click()}><Upload size={17}/>{busy?"Importando…":"Importar"}</button><button className="admin-primary" onClick={()=>{setDraft(null);setCurrent(null)}}>+ Nuevo documento</button></div></div>
  {error&&<p className="admin-error docs-alert">{error}</p>}
  <label className="docs-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar en la documentación…"/></label>
  {filtered.length?<div className="docs-grid">{filtered.map(doc=><button className="doc-card doc-button" onClick={()=>{setDraft(null);setCurrent(doc)}} key={doc.id}><FileText size={26}/><h2>{doc.title}</h2><p>{doc.content.slice(0,130)||"Documento vacío"}</p><small>{doc.category} · {new Date(doc.updated_at).toLocaleDateString("es")}</small></button>)}</div>:<div className="workspace-state">No hay documentos. Crea o importa el primero.</div>}
  {current!==undefined&&<Modal title={current?"Editar documento":draft?"Revisar importación":"Nuevo documento"} onClose={close}><form className="workspace-form document-editor-form" onSubmit={submit}><label>Título<input name="title" defaultValue={current?.title||draft?.title||""} required/></label><label>Categoría<select name="category" defaultValue={current?.category||draft?.category||"Notas"}>{["Especificaciones","Arquitectura","Casos de uso","Diagramas","Manual del sistema","Notas","Documentación técnica","PDF importado","Word importado"].map(x=><option key={x}>{x}</option>)}</select></label><label className="full">Contenido<textarea className="doc-editor" name="content" defaultValue={current?.content||draft?.content||""} rows={10}/></label>{current&&<div className="document-export full"><span><Download size={16}/> Exportar como</span>{["pdf","docx","md","txt"].map(format=><a key={format} href={`/api/admin/documents/export?id=${encodeURIComponent(current.id)}&format=${format}`} download>{format.toUpperCase()}</a>)}</div>}<footer className="form-actions document-actions full">{current&&<button type="button" className="danger-button" onClick={async()=>{if(!confirm(`¿Eliminar “${current.title}”? Esta acción no se puede deshacer.`))return;setError("");try{await remove("document",current.id);close()}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo eliminar el documento.")}}}><Trash2 size={16}/> Eliminar documento</button>}<button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="admin-primary">{draft?"Importar y guardar":"Guardar documento"}</button></footer></form></Modal>}
 </WorkspaceState>
}
